// ==============================================================================
// Document.cpp - Document Data Structure Implementation
// ==============================================================================
// PURPOSE: Implement the Document struct
// A Document represents a source code file with its raw content and
// processed tokens for plagiarism analysis
// ==============================================================================

#include "Document.hpp"  // Include the Document header

namespace pd {

// NOTE: Document is a struct (plain data holder), not a class with complex logic
// It contains:
// - path: file system path to the document
// - rawText: original unprocessed source code
// - tokens: processed tokens after analysis
//
// No special implementation needed - the struct is handled by the compiler
// The constructor is implicitly generated by C++

} // namespace pd (end of namespace)
